-- ============================================================================
-- 007 — NEUTRALIZZATA · NON APPLICARE IL CONTENUTO ORIGINALE
-- ============================================================================
--
--   Il contenuto originale apriva in lettura anonima l'intero archivio ordini
--   della piattaforma. Le policy che definisce erano attive in produzione e
--   sono state rimosse con un DROP POLICY manuale, prima che l'audit avesse
--   visibilità sul progetto: cfr. AUDIT_REPORT.md, sezione "Risolti —
--   intervento diretto sul database", rilievo C1. Come siano arrivate in
--   produzione — da questo file o da un intervento separato — non è
--   documentato e resta una domanda aperta.
--
-- CONTENUTO ORIGINALE (conservato solo come documentazione, NON eseguirlo):
--
--     CREATE POLICY "orders: public read" ON public.orders
--       FOR SELECT USING (true);
--     CREATE POLICY "order_items: public read" ON public.order_items
--       FOR SELECT USING (true);
--
-- PERCHÉ È PERICOLOSO
--   `USING (true)` su una SELECT rende la tabella leggibile da chiunque
--   possieda la chiave anon — che è pubblica per costruzione, essendo inclusa
--   nel bundle JavaScript servito a ogni visitatore. Le policy permissive si
--   sommano in OR, quindi questa avrebbe annullato "orders: owner read".
--
--   Sarebbero diventati leggibili da chiunque, per tutti i ristoranti:
--   customer_name, customer_email, customer_phone, customer_address, notes,
--   total. Un archivio di dati personali esposto integralmente.
--
--   Il ruolo `anon` ha un GRANT SELECT di tabella su `orders` e `order_items`
--   (impostazione predefinita Supabase), quindi non esiste alcuna restrizione
--   per colonna che faccia da rete di sicurezza: l'unica difesa è l'assenza di
--   una policy permissiva. Vedere la sezione PRIVILEGI_anon di
--   lo script di ricognizione dello schema (non versionato).
--
-- MOTIVO ORIGINALE E ALTERNATIVA CORRETTA
--   Serviva a mostrare al cliente lo stato del proprio ordine nella pagina di
--   tracking. Quel caso d'uso è già coperto da /api/order-status/[orderId],
--   che gira lato server con la service role key, cerca per UUID e
--   restituisce i soli campi che la pagina di tracking mostra, senza alcun
--   dato personale del cliente (nome, email, telefono). Cfr. rilievo N9.
--
-- Il file è conservato, vuoto di effetti, per non alterare la numerazione
-- della sequenza di migration. Cfr. AUDIT_REPORT.md, rilievo C1.
-- ============================================================================

-- Nessuna operazione.
SELECT 1;
